---
output: md_document
---

# GP Responses -- Figures

```{r setup, include = FALSE}
library(coda)
library(forcats)
library(fuzzyjoin)
library(ggnuplot)
library(ggplot2)
library(here)
library(scales)
library(stringr)

source(here("figures", "utils.R"))
dir.create(here("figures", "output"))

source(here("simulation", "scenarios.R"))
dir.create(here("simulation", "output"))

knitr::knit_hooks$set(crop = knitr::hook_pdfcrop)

knitr::opts_chunk$set(
  dev        = "cairo_pdf",
  fig.path   = here("figures", "output/"),
  fig.width  = 8,
  fig.height = 4,
  crop       = TRUE,
  echo       = FALSE,
  results    = "hide",
  message    = FALSE
)
```

```{r session, echo = TRUE, results = "markup"}
Sys.time()
devtools::session_info()
system2("git", "log -1", stdout = TRUE)
system2("git", "diff", stdout = TRUE)
set.seed(1337)
```

## Joint sampling

```{r joint-bias}
load(here("simulation", "output", "joint-grid.RData"))
grid <- as_tibble(grid)

N <- grid$N[1]
n <- grid$n[1]

large <- do.call(joint, c(grid[1,], intercept =  0))
small <- do.call(joint, c(grid[1,], intercept = -3))

df <- map_dfr(1:nrow(grid), function(i) {
  load(here("simulation", "output", sprintf("joint-%03d-large.RData", i)))

  s1 <- tidy_samples(samples(joint$model))
  s2 <- tidy_samples(joint$samples)

  load(here("simulation", "output", sprintf("joint-%03d-small.RData", i)))

  s3 <- tidy_samples(samples(joint$model))
  s4 <- tidy_samples(joint$samples)

  s1 <- tibble(grid[i,], range = "large", sampler = "separate", s1)
  s2 <- tibble(grid[i,], range = "large", sampler = "joint", s2)
  s3 <- tibble(grid[i,], range = "small", sampler = "separate", s3)
  s4 <- tibble(grid[i,], range = "small", sampler = "joint", s4)

  bind_rows(s1, s2, s3, s4)
})

df$covariate <- factor(df$covariate)

df$predictor <- factor(
  x = df$predictor,
  levels = c("mean", "stddev", "range"),
  labels = c("μ", "σ", "ϕ")
)

df$range <- factor(
  x = df$range,
  levels = c("large", "small"),
  labels = c("Large", "Small")
)

df$sampler <- factor(
  x = df$sampler,
  levels = c("joint", "separate"),
  labels = c("Joint", "Separate")
)

smmry <- df %>%
  filter(iteration > 200) %>%
  group_by_at(vars(-iteration, -sample)) %>%
  summarize(pmean = mean(sample), ess = effectiveSize(sample)) %>%
  ungroup()

true <- tribble(
  ~predictor,    ~covariate, ~value,
      "mean", "(Intercept)",      0,
      "mean",          "x1",      1,
    "stddev", "(Intercept)",      0,
    "stddev",          "x2",      1,
    "stddev",          "x4",      1,
     "range", "(Intercept)",     NA,
     "range",          "x3",      1,
     "range",          "x4",      1
)

true$covariate <- factor(true$covariate)

true$predictor <- factor(
  x = true$predictor,
  levels = c("mean", "stddev", "range"),
  labels = c("μ", "σ", "ϕ")
)

smmry <- left_join(smmry, true) %>%
  mutate(
    value = case_when(
      range == "Large" & is.na(value) ~  0,
      range == "Small" & is.na(value) ~ -3,
      TRUE ~ value
    ),
    bias = pmean - value,
    predictor_covariate = fct_rev(fct_inorder(
      f = paste(predictor, covariate, sep = ": "),
    ))
  )

label_range <- function(labels) {
  out <- label_both(labels)
  out <- map(out, str_replace, pattern = "range", replacement = "Range")
  out
}

ggplot(smmry, aes(predictor_covariate, bias, fill = sampler)) +
  geom_boxplot() +
  geom_hline(yintercept = 0) +
  coord_flip() +
  facet_wrap(vars(range), labeller = label_range) +
  xlab(NULL) +
  ylab("Bias") +
  ylim(-5, 5) +
  scale_fill_gnuplot(name = "Sampler", limits = rev(levels(smmry$sampler))) +
  theme_gnuplot(base_family = "TeXGyreHeros") +
  theme(panel.grid = element_line(color = "gray"))
```

```{r joint-ess}
ggplot(filter(smmry, range == "Large"),
       aes(predictor_covariate, ess, fill = sampler)) +
  geom_boxplot() +
  coord_flip() +
  xlab(NULL) +
  ylab(NULL) +
  scale_fill_gnuplot(name = "Sampler", limits = rev(levels(smmry$sampler))) +
  theme_gnuplot(base_family = "TeXGyreHeros") +
  theme(panel.grid = element_line(color = "gray"))
```

```{r joint-response}
df <- data.frame(
  i = rep(seq(1, 2 * N), each = n),
  s = rep(large$s, times = N * n),
  y = c(simplify(large$y), simplify(small$y)),
  Range = rep(c("Large", "Small"), each = N * n)
)

ggplot(df, aes(s, y, color = Range, group = i)) +
  geom_line(alpha = 0.7, size = 0.5) +
  geom_hline(aes(yintercept = 0, color = Range), size = 1) +
  facet_wrap(vars(Range), labeller = label_both) +
  xlab("t") +
  scale_x_gnuplot(expand = c(0, 0)) +
  scale_y_gnuplot(breaks = waiver(), limits = c(-11, 11), oob = oob_keep) +
  scale_color_gnuplot() +
  theme_gnuplot(base_family = "TeXGyreHeros") +
  theme(legend.position = "none")
```

```{r joint-trace, fig.height = 5}
df <- data.frame(
  Sampling = rep(c("Separate", "Joint"), each = 4000),
  Range = rep(rep(c("Large", "Small"), times = 2), each = 2000),
  Predictor = rep(rep(c("σ", "ϕ"), times = 4), each = 1000),
  Iteration = rep(1:1000, times = 8),
  Sample = c(
    samples(large$model)[1:1000, "stddev.p.x4"],
    samples(large$model)[1:1000, "range.p.x4"],
    samples(small$model)[1:1000, "stddev.p.x4"],
    samples(small$model)[1:1000, "range.p.x4"],
    large$joint$samples$stddev$p[201:1200, "x4"],
    large$joint$samples$range$p[201:1200, "x4"],
    small$joint$samples$stddev$p[201:1200, "x4"],
    small$joint$samples$range$p[201:1200, "x4"]
  )
)

df$Predictor <- fct_inorder(df$Predictor)
df$Sampling <- fct_inorder(df$Sampling)

label_range <- function(labels) {
  out <- label_both(labels)
  out <- map(out, str_replace, pattern = "Range", replacement = "ϕ")
  out
}

ggplot(df, aes(Iteration, Sample, color = Range)) +
  geom_line(alpha = 0.7, size = 0.3) +
  geom_smooth(se = FALSE) +
  facet_grid(vars(Range, Predictor), vars(Sampling), labeller = label_range) +
  ylab(NULL) +
  scale_x_gnuplot(expand = c(0, 0)) +
  scale_y_gnuplot(breaks = waiver(), limits = c(-0.5, 2.5), oob = oob_keep) +
  scale_color_gnuplot() +
  theme_gnuplot(base_family = "TeXGyreHeros") +
  theme(legend.position = "none")
```

## Time-varying covariates

```{r covariates-bias}
load(here("simulation", "output", "covariates-grid.RData"))
grid <- as_tibble(grid)

env <- do.call(covariates, grid[1,])

df <- map_dfr(1:nrow(grid), function(i) {
  load(here("simulation", "output", sprintf("covariates-%03d.RData", i)))
  tibble(grid[i,], tidy_samples(joint$samples))
})

df$covariate <- factor(df$covariate)

df$predictor <- factor(
  x = df$predictor,
  levels = c("limit", "shape", "scale", "linear1", "stddev", "range"),
  labels = c("l", "a", "b", "w", "σ", "ϕ")
)

smmry <- df %>%
  filter(iteration > 200) %>%
  group_by_at(vars(-iteration, -sample)) %>%
  summarize(pmean = mean(sample), ess = effectiveSize(sample)) %>%
  ungroup()

true <- tribble(
  ~predictor,    ~covariate,    ~value,
     "limit", "(Intercept)", log(1500),
     "shape", "(Intercept)",  log(3.5),
     "scale", "(Intercept)",  log(100),
   "linear1", "(Intercept)",         0,
   "linear1",           "x",         1,
    "stddev", "(Intercept)",   log(40),
     "range", "(Intercept)",    log(2)
)

true$covariate <- factor(true$covariate)

true$predictor <- factor(
  x = true$predictor,
  levels = c("limit", "shape", "scale", "linear1", "stddev", "range"),
  labels = c("l", "a", "b", "w", "σ", "ϕ")
)

smmry <- left_join(smmry, true) %>%
  mutate(
    bias = pmean - value,
    predictor_covariate = fct_inorder(str_remove(
      string = paste(predictor, covariate, sep = ": "),
      pattern = "(?<!w): \\(Intercept\\)"
    )),
    N = fct_inseq(as.character(N))
  )

ggplot(smmry, aes(predictor_covariate, bias, fill = N)) +
  geom_boxplot() +
  geom_hline(yintercept = 0) +
  facet_grid(rows = vars(n), labeller = label_both) +
  xlab(NULL) +
  ylab("Bias") +
  ylim(-0.3, 0.5) +
  scale_fill_gnuplot() +
  theme_gnuplot(base_family = "TeXGyreHeros") +
  theme(panel.grid = element_line(color = "gray"))
```

```{r covariates-response}
N <- 30 # 170 in the application
n <- 60 # ~180 in the application

df <- data.frame(
  i = rep(seq(1, 2 * N), each = n),
  s = rep(env$s[[1]], times = 2 * N),
  y = c(do.call(c, env$y), do.call(c, env$Z)),
  Curve = fct_inorder(rep(c("y", "u"), each = N * n))
)

m <- data.frame(
  i = rep(c(1, 2), each = n),
  s = rep(env$s[[1]], times = 2),
  y = c(
    bamlssGP:::m_fun(env$s[[1]], env$limit, env$shape, env$scale),
    rep(0, times = n)
  ),
  Curve = fct_inorder(rep(c("y", "u"), each = n))
)

ggplot(df, aes(s, y, color = Curve, group = i)) +
  geom_line(alpha = 0.7, size = 0.3) +
  geom_line(data = m, size = 1) +
  facet_wrap(vars(Curve)) +
  xlab("t") +
  ylab(NULL) +
  scale_x_gnuplot(
    breaks = c(29, 60, 90, 121, 152),
    labels = c("May 1", "Jun 1", "Jul 1", "Aug 1", "Sep 1"),
    expand = c(0, 0)
  ) +
  scale_y_gnuplot(breaks = waiver()) +
  scale_color_gnuplot() +
  theme_gnuplot(base_family = "TeXGyreHeros") +
  theme(legend.position = "none")
```

```{r covariates-trace}
df <- data.frame(
  Covariate = rep(c("(Intercept)", "x"), each = 1000),
  Iteration = rep(1:1000, times = 2),
  Sample = c(
    env$joint$samples$linear1$p[201:1200, "(Intercept)"],
    env$joint$samples$linear1$p[201:1200, "x"]
  )
)

ggplot(df, aes(Iteration, Sample)) +
  geom_line(alpha = 0.7, color = gnucolors[1], size = 0.3) +
  geom_smooth(color = gnucolors[1], se = FALSE) +
  facet_wrap(vars(Covariate), scales = "free_y", labeller = label_both) +
  ylab(NULL) +
  scale_x_gnuplot(expand = c(0, 0)) +
  scale_y_gnuplot(breaks = waiver()) +
  theme_gnuplot(base_family = "TeXGyreHeros") +
  theme(legend.position = "none", panel.spacing = unit(0.3, "inches"))
```

## Processes on a sphere

```{r sphere-bias}
load(here("simulation", "output", "sphere-grid.RData"))
grid <- as_tibble(grid)

env <- do.call(sphere, grid[19,])

df <- map_dfr(1:nrow(grid), function(i) {
  load(here("simulation", "output", sprintf("sphere-%03d.RData", i)))
  tibble(grid[i,], tidy_samples(joint$samples))
})

df$covariate <- factor(df$covariate)

df$predictor <- factor(
  x = df$predictor,
  levels = c("radius", "south", "height", "stddev", "range"),
  labels = c("r", "h", "v", "σ", "ϕ")
)

smmry <- df %>%
  filter(iteration > 200) %>%
  group_by_at(vars(-iteration, -sample)) %>%
  summarize(pmean = mean(sample), ess = effectiveSize(sample)) %>%
  ungroup()

true <- tribble(
  ~predictor,    ~covariate, ~value,
    "radius", "(Intercept)",      0,
    "radius",          "x1",      1,
     "south", "(Intercept)",      0,
     "south",          "x2",      1,
    "height", "(Intercept)",      1,
    "height",          "x3",      1,
    "stddev", "(Intercept)",      0,
    "stddev",          "x4",      1,
     "range", "(Intercept)",      0,
     "range",          "x5",      1
)

true$covariate <- factor(true$covariate)

true$predictor <- factor(
  x = true$predictor,
  levels = c("radius", "south", "height", "stddev", "range"),
  labels = c("r", "h", "v", "σ", "ϕ")
)

smmry <- left_join(smmry, true) %>%
  mutate(
    bias = pmean - value,
    mse = (pmean - value)^2,
    predictor_covariate = fct_inorder(
      f = paste(predictor, covariate, sep = ": "),
    )
  )

smmry %>%
  group_by(predictor_covariate) %>%
  summarize(bias = round(mean(bias), 3), mse = round(mean(mse), 3)) %>%
  arrange(desc(bias))

ggplot(smmry, aes(predictor_covariate, bias)) +
  geom_boxplot(fill = gnucolors[1]) +
  geom_hline(yintercept = 0) +
  xlab(NULL) +
  ylab("Bias") +
  theme_gnuplot() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_line(color = "gray")
  )
```

```{r sphere-response}
df <- expand.grid(
  lat = seq.int(-90, 90, length.out = 15),
  lon = seq.int(-180, 180, length.out = 30)
)

tmp <- data.frame(
  lon = env$s[[1]][, 1] * (180 / pi),
  lat = env$s[[1]][, 2] * (180 / pi),
  m = env$m[[1]],
  y = env$y[[1]]
)

df <- geo_left_join(df, tmp, by = c("lon", "lat"), method = "cosine")
df <- data.frame(lon = df$lon.x, lat = df$lat.x, m = df$m, y = df$y)

dat_path <- here("figures", "sphere", "sphere.dat")

write.table(df, dat_path, quote = FALSE, row.names = FALSE)

# add empty lines as described in the gnuplot docs:
# http://www.gnuplot.info/docs_5.2/Gnuplot_5.2.pdf, p. 196

lines <- readLines(dat_path)
newline <- which(diff(df$lon) > 0) + 1
lines[newline] <- paste0(lines[newline], "\n")
writeLines(lines, dat_path)

m_pdf_path <- here("figures", "sphere", "sphere-m.pdf")
y_pdf_path <- here("figures", "sphere", "sphere-y.pdf")
m_y_pdf_path <- here("figures", "output", "sphere-response-1.pdf")

system(paste("cd", here("figures", "sphere"), "&& gnuplot sphere.gp"))

system2("pdfcrop", c("--margin 10", m_pdf_path, m_pdf_path))
system2("pdfcrop", c("--margin 10", y_pdf_path, y_pdf_path))

system2("pdfjam", c("--landscape --nup 2x1 --outfile", m_y_pdf_path,
                    m_pdf_path, y_pdf_path))

system2("pdfcrop", c(m_y_pdf_path, m_y_pdf_path))
```
